apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  selector:
    matchLabels:
      app: user-service
  template:
    spec:
      containers:
        - name: user-service
          image: registry.cn-hangzhou.aliyuncs.com/sg-exam/user-service
          imagePullPolicy: Never
          env:
          - name: SPRING_PROFILES_ACTIVE
            value: "docker,prod"
          resources:
            limits:
              memory: 512Mi