server:
  port: 80
  servlet:
    context-path: /auth-service
spring.application.name: auth-service

# mybatis配置
mybatis:
  type-aliases-package: com.github.tangyi.api.auth.module
  configuration:
    # 驼峰转换
    map-underscore-to-camel-case: true
    # 延迟加载
    lazy-loading-enabled: true
  mapper-locations: classpath:mapper/*.xml
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# 集群ID生成配置
cluster:
  workId: 1
  dataCenterId: 1

# 微信配置
wx:
  appId: ${WX_APP_ID:test}
  appSecret: ${WX_APP_SECRET:test}
  grantType: ${WX_GRANT_TYPE:authorization_code}

---
server:
  port: 9182
spring:
  profiles: dev

# 集群ID生成配置
cluster:
  workId: 1
  dataCenterId: 1

# 日志文件名称
logging:
  file: auth-service.log
logback:
  loglevel: warn

---
spring:
  profiles: docker
  port: 80
  datasource:
    url: jdbc:mysql://sg-exam-mysql/microservice-auth?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=CTT&characterEncoding=UTF-8
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: redis

# 系统配置
sys:
  adminUser: admin  # 管理员账号，默认是admin
  uploadUrl: api/user/v1/attachment/upload
  defaultAvatar: /static/img/avatar/
  key: '1234567887654321'
  cacheExpire: 86400 # 缓存失效时间，单位秒，默认一天
  attachtUploadType: 1  # 上传类型，1：本地目录，2：fastDfs，3：七牛云
  attachPath: ${ATTACH_PATH:C:/attach} # 附件上传目录
  canPreview: jpg,png,jpeg,gif # 支持预览的格式
  authServiceUrl: http://auth-service.sg-exam.svc.cluster.local/auth-service
  userServiceUrl: http://user-service.sg-exam.svc.cluster.local/user-service
  examServiceUrl: http://exam-service.sg-exam.svc.cluster.local/exam-service

---
spring:
  profiles: prod
  port: 80
  datasource:
    url: jdbc:mysql://mysql/microservice-auth?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=CTT&characterEncoding=UTF-8
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: redis

logging:
  level:
    root: WARN