server:
  port: 80
  servlet:
    context-path: /exam-service
spring.application.name: exam-service

# 系统配置
sys:
  cacheExpire: 86400 # 缓存失效时间，单位秒，默认一天
  logoUrl: /static/img/exam
  logoCount: 22
  logoSuffix: .jpeg
  qrCodeUrl: http://${QR_CODE_URL:localhost}:${QR_CODE_PORT:8080}/#/mobile

ignore:
  urls:
    - /
    - /**/error
    - /**/favicon.ico
    - /**/**/*swagger*/**
    - /**/v2/api-docs
    - /**/csrf
    - /**/actuator/**
    - /**/hystrix.sender
    - /**/v1/sms/**
    - /**/v1/examination/anonymousUser/**
    - /**/v1/answer/anonymousUser/**
    - /**/v1/examRecord/anonymousUser/**
    - /**/v1/examRecord/currentTime
    - /**/v1/subject/anonymousUser/**
    - /**/v1/answer/anonymousUser/**
    - /**/*.css
    - /**/*.js
    - /**/social
    - /**/signin
    - /**/signup
    - /**/info
    - /**/health
    - /**/metrics/**
    - /**/loggers/**

# 集群ID生成配置
cluster:
  workId: 1
  dataCenterId: 1

---
server:
  port: 9184
spring:
  profiles: dev
  datasource:
    dataSourceClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MYSQL
    initialize: true
    username: sa
    password:

---
spring:
  profiles: docker
  port: 80
  datasource:
    url: jdbc:mysql://sg-exam-mysql/sg-exam-exam?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=CTT&characterEncoding=UTF-8
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: redis

# 系统配置
sys:
  adminUser: admin  # 管理员账号，默认是admin
  uploadUrl: api/user/v1/attachment/upload
  defaultAvatar: /static/img/avatar/
  key: '1234567887654321'
  cacheExpire: 86400 # 缓存失效时间，单位秒，默认一天
  attachUploadType: 3  # 上传类型，3：七牛云
  attachPath: ${ATTACH_PATH:C:/attach} # 附件上传目录
  canPreview: jpg,png,jpeg,gif # 支持预览的格式
  authServiceUrl: http://auth-service.sg-exam.svc.cluster.local/auth-service
  userServiceUrl: http://user-service.sg-exam.svc.cluster.local/user-service
  examServiceUrl: http://exam-service.sg-exam.svc.cluster.local/exam-service

---
spring:
  profiles: prod
  port: 80
  datasource:
    url: jdbc:mysql://sg-exam-mysql/sg-exam-exam?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=CTT&characterEncoding=UTF-8
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: redis