server:
  port: 80
  servlet:
    context-path: /msc-service
spring.application.name: msc-service

# 集群ID生成配置
cluster:
  workId: 1
  dataCenterId: 1

# 短信配置
sms:
  appKey: ${SMS_APP_KEY:test}
  appSecret: ${SMS_APP_SECRET:test}
  regionId: ${SMS_REGION_ID:default}
  domain: ${SMS_DOMAIN:dysmsapi.aliyuncs.com}
  signName: ${SMS_SIGN_NAME:test}
  templateCode: ${SMS_TEMP_CODE:SMS_171192294}
  version: ${SMS_VERSION:2017-05-25}
  action: ${SMS_ACTION:SendSms}

---
server:
  port: 0
spring:
  profiles: dev
# 日志文件名称
logging:
  file: msc-service.log
logback:
  loglevel: warn

---
spring:
  profiles: docker
  port: 80
  redis:
    host: redis

# 系统配置
sys:
  adminUser: admin  # 管理员账号，默认是admin
  uploadUrl: api/user/v1/attachment/upload
  defaultAvatar: /static/img/avatar/
  key: '1234567887654321'
  cacheExpire: 86400 # 缓存失效时间，单位秒，默认一天
  attachtUploadType: 1  # 上传类型，1：本地目录，2：fastDfs，3：七牛云
  attachPath: ${ATTACH_PATH:C:/attach} # 附件上传目录
  canPreview: jpg,png,jpeg,gif # 支持预览的格式
  authServiceUrl: http://auth-service.sg-exam.svc.cluster.local/auth-service
  userServiceUrl: http://user-service.sg-exam.svc.cluster.local/user-service
  examServiceUrl: http://exam-service.sg-exam.svc.cluster.local/exam-service
