server.port: 80
spring.application.name: user-service

# 集群ID生成配置
cluster:
  workId: 1
  dataCenterId: 1

---
server:
  port: 9183
spring:
  profiles: dev
  datasource:
    dataSourceClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MYSQL
    initialize: true
    username: sa
    password:

# 日志文件名称
logging:
  file: user-service.log
logback:
  loglevel: warn

---
spring:
  profiles: docker
  port: 80
  servlet:
    multipart:
      # 单个文件的大小
      max-file-size: 10MB
      # 单次请求的文件的总大小
      max-request-size: 100MB
  datasource:
    url: jdbc:mysql://mysql/microservice-user?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=CTT&characterEncoding=UTF-8
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: redis

# ===================================================================
# 分布式文件系统FDFS配置
# ===================================================================
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:            #TrackerList参数,支持多个
    - ${FDFS_HOST:192.168.0.95}:${FDFS_PORT:22122}

# ===================================================================
# 七牛云存储配置
# ===================================================================
qiniu:
  access-key: ${QINIU_ACCEESS_KEY:test}
  secret-key: ${QINIU_SECRET_KEY:test}
  bucket: microservice-exam
  domain-of-bucket: ${QINIU_DOMAIN:test}
  expire: 3600  # 链接超时时间，单位秒，默认一小时

---
spring:
  profiles: prod
  port: 8080
  datasource:
    url: jdbc:mysql://mysql/microservice-user?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=CTT&characterEncoding=UTF-8
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: redis

logging:
  level:
    root: WARN