apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
        version: v2
    spec:
      containers:
        - name: auth-service
          image: registry.cn-hangzhou.aliyuncs.com/sg-exam/auth-service:v2
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker,prod"
          resources:
            limits:
              memory: 512Mi
