apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-service
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "4004"
        prometheus.io/scheme: http
        prometheus.io/path: "/actuator/prometheus"
      labels:
        app: admin-service
        version: latest
    spec:
      containers:
        - name: admin-service
          image: registry.cn-hangzhou.aliyuncs.com/sg-exam/admin-service
          imagePullPolicy: Never
          ports:
            - containerPort: 80