apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
        version: latest
    spec:
      containers:
        - name: user-service
          image: registry.cn-hangzhou.aliyuncs.com/sg-exam/user-service
          imagePullPolicy: Never
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
            - name: SPRING_CONFIG_LOCATION
              value: file:/config-repo/application.yml,file:/config-repo/user-service.yml
          envFrom:
            - secretRef:
                name: redis-credentials
            - secretRef:
                name: mysql-credentials
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: 512Mi
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /user-service/actuator/info
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 20
            successThreshold: 1
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /user-service/actuator/health
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
            successThreshold: 1
          volumeMounts:
            - name: config-repo-volume
              mountPath: /config-repo
      volumes:
        - name: config-repo-volume
          configMap:
            name: config-repo-user-service